language: node_js
node_js:
  - "4"
branches:
  only:
    - master
before_script:
  - npm install -g bower
  - npm install -g gulp
  - npm install
  - bower install
  - gulp build
  
after_script:
  - gulp build
